baseurl             = "https://qezwan.ir"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishDir          = "docs"
theme               = "cocoa"
author              = "Qezwan"
title               = "Qezwan"
pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-115800084-1"
pygmentsStyle = "tango"

PostLimit = 5
[permalinks]
book  = "book/:slug/"

[outputs]
  home = ["html", "json"]

[[menu.main]]
name                   = "دەربارە"
weight                 = -100
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "کتێب"
weight                 = -110
identifier             = "code"
url                    = "/book/"

[[menu.main]]
name                   = "لینوکس"
weight                 = -130
identifier             = "learn"
url                    = "https://linux.krd"
theme = ["hugo-video", "cocoa"]

[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "قەزوان"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
#email                  = "you@example.space"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/qezwan/blog"
#instagram              = "//instagram.com/qezwan"
#px500                  = "//500px.com/username"
lang                   = "en"
#linkedin               = "//linkedin.com/in/you"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/qezwan"
#mastodon               = "//example.com/@you"
telegram               = "//t.me/jsajjadi"

highlightjs            = true
#highlightjslanguages = ["go,sql,mysql,html,php,c#,csharp,css"]                        # additional languages not included in the "common" set
#highlightjsStyle     = "Lightfair"

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik

gitalk                 = false
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
gitalk_clientID        = "your client id"
gitalk_clientSecret    = "your client secret"
gitalk_repo            = "your repo url"
gitalk_owner           = "the owner of this repo"
gitalk_admin           = ['a', 'list', 'of', 'administrator']
[params.social.share]  
 twitter = true
  
#avatar                 = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
gravatar             = "38a4cd08cd8c0de387d0a8e3086cfdc0"                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
[params.mysite]

taxonomy = "/learn/gimp/"

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

 
